// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/master_service.proto

module tensorflow.grpc.master_service;

import google.protobuf;
import tensorflow.master;

enum protocVersion = 3012004;
