// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker_service.proto

module tensorflow.grpc.worker_service;

import google.protobuf;
import tensorflow.worker;

enum protocVersion = 3012004;
