// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/remote_tensor_handle.proto

module tensorflow.eager.remote_tensor_handle;

import google.protobuf;
import tensorflow.tensor_shape;
import tensorflow.types;

enum protocVersion = 3012004;

class ResourceDtypeAndShape
{
    @Proto(1) DataType dtype = protoDefaultValue!(DataType);
    @Proto(2) TensorShapeProto shape = protoDefaultValue!(TensorShapeProto);
}

class RemoteTensorHandle
{
    @Proto(1) long opId = protoDefaultValue!(long);
    @Proto(2) int outputNum = protoDefaultValue!(int);
    @Proto(3) string device = protoDefaultValue!(string);
    @Proto(4) string opDevice = protoDefaultValue!(string);
    @Proto(5) DataType dtype = protoDefaultValue!(DataType);
    @Proto(6) ResourceDtypeAndShape[] resourceDtypesAndShapes = protoDefaultValue!(ResourceDtypeAndShape[]);
}
