// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/allocation_description.proto

module tensorflow.allocation_description;

import google.protobuf;

enum protocVersion = 3012004;

class AllocationDescription
{
    @Proto(1) long requestedBytes = protoDefaultValue!(long);
    @Proto(2) long allocatedBytes = protoDefaultValue!(long);
    @Proto(3) string allocatorName = protoDefaultValue!(string);
    @Proto(4) long allocationId = protoDefaultValue!(long);
    @Proto(5) bool hasSingleReference = protoDefaultValue!(bool);
    @Proto(6) ulong ptr = protoDefaultValue!(ulong);
}
