// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/api_def.proto

module tensorflow.api_def;

import google.protobuf;
import tensorflow.attr_value;

enum protocVersion = 3012004;

class ApiDef
{
    @Proto(1) string graphOpName = protoDefaultValue!(string);
    @Proto(2) Visibility visibility = protoDefaultValue!(Visibility);
    @Proto(3) ApiDef.Endpoint[] endpoint = protoDefaultValue!(ApiDef.Endpoint[]);
    @Proto(4) ApiDef.Arg[] inArg = protoDefaultValue!(ApiDef.Arg[]);
    @Proto(5) ApiDef.Arg[] outArg = protoDefaultValue!(ApiDef.Arg[]);
    @Proto(6) ApiDef.Attr[] attr = protoDefaultValue!(ApiDef.Attr[]);
    @Proto(7) string summary = protoDefaultValue!(string);
    @Proto(8) string description = protoDefaultValue!(string);
    @Proto(9) string descriptionPrefix = protoDefaultValue!(string);
    @Proto(10) string descriptionSuffix = protoDefaultValue!(string);
    @Proto(11) string[] argOrder = protoDefaultValue!(string[]);
    @Proto(12) string deprecationMessage = protoDefaultValue!(string);
    @Proto(13) int deprecationVersion = protoDefaultValue!(int);

    static class Endpoint
    {
        @Proto(1) string name = protoDefaultValue!(string);
        @Proto(3) bool deprecated_ = protoDefaultValue!(bool);
        @Proto(4) int deprecationVersion = protoDefaultValue!(int);
    }

    static class Arg
    {
        @Proto(1) string name = protoDefaultValue!(string);
        @Proto(2) string renameTo = protoDefaultValue!(string);
        @Proto(3) string description = protoDefaultValue!(string);
    }

    static class Attr
    {
        @Proto(1) string name = protoDefaultValue!(string);
        @Proto(2) string renameTo = protoDefaultValue!(string);
        @Proto(3) AttrValue defaultValue = protoDefaultValue!(AttrValue);
        @Proto(4) string description = protoDefaultValue!(string);
    }

    enum Visibility
    {
        DEFAULT_VISIBILITY = 0,
        VISIBLE = 1,
        SKIP = 2,
        HIDDEN = 3,
    }
}

class ApiDefs
{
    @Proto(1) ApiDef[] op = protoDefaultValue!(ApiDef[]);
}
