// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/autotuning.proto

module tensorflow.autotuning;

import google.protobuf;
import google.protobuf.any;
import google.protobuf.duration;

enum protocVersion = 3012004;

class CudnnVersion
{
    @Proto(1) int major = protoDefaultValue!(int);
    @Proto(2) int minor = protoDefaultValue!(int);
    @Proto(3) int patch = protoDefaultValue!(int);
}

class ComputeCapability
{
    @Proto(1) int major = protoDefaultValue!(int);
    @Proto(2) int minor = protoDefaultValue!(int);
}

class AutotuneResult
{
    enum KeyCase
    {
        keyNotSet = 0,
        conv = 5,
        gemm = 6,
    }
    KeyCase _keyCase = KeyCase.keyNotSet;
    @property KeyCase keyCase() { return _keyCase; }
    void clearKey() { _keyCase = KeyCase.keyNotSet; }
    @Oneof("_keyCase") union
    {
        @Proto(5) AutotuneResult.ConvKey _conv = protoDefaultValue!(AutotuneResult.ConvKey); mixin(oneofAccessors!_conv);
        @Proto(6) AutotuneResult.GemmKey _gemm; mixin(oneofAccessors!_gemm);
    }
    @Proto(7) AutotuneResult.FailureResult failure = protoDefaultValue!(AutotuneResult.FailureResult);
    @Proto(8) long scratchBytes = protoDefaultValue!(long);
    @Proto(9) Duration runTime = protoDefaultValue!(Duration);

    static class FailureResult
    {
        @Proto(1) FailureKind kind = protoDefaultValue!(FailureKind);
        @Proto(2) string msg = protoDefaultValue!(string);
        enum KeyCase
        {
            keyNotSet = 0,
            referenceConv = 11,
            referenceGemm = 12,
        }
        KeyCase _keyCase = KeyCase.keyNotSet;
        @property KeyCase keyCase() { return _keyCase; }
        void clearKey() { _keyCase = KeyCase.keyNotSet; }
        @Oneof("_keyCase") union
        {
            @Proto(11) AutotuneResult.ConvKey _referenceConv = protoDefaultValue!(AutotuneResult.ConvKey); mixin(oneofAccessors!_referenceConv);
            @Proto(12) AutotuneResult.GemmKey _referenceGemm; mixin(oneofAccessors!_referenceGemm);
        }
        @Proto(13) long bufferAddress = protoDefaultValue!(long);
    }

    static class ConvKey
    {
        @Proto(1) long algorithm = protoDefaultValue!(long);
        @Proto(2) bool tensorOpsEnabled = protoDefaultValue!(bool);
    }

    static class GemmKey
    {
        @Proto(1) long algorithm = protoDefaultValue!(long);
    }

    enum FailureKind
    {
        UNKNOWN = 0,
        REDZONE_MODIFIED = 1,
        WRONG_RESULT = 2,
    }
}

class AutotuningLog
{
    @Proto(1) Any instr = protoDefaultValue!(Any);
    @Proto(2) AutotuneResult[] results = protoDefaultValue!(AutotuneResult[]);
    @Proto(3) CudnnVersion cudnnVersion = protoDefaultValue!(CudnnVersion);
    @Proto(4) ComputeCapability computeCapability = protoDefaultValue!(ComputeCapability);
    @Proto(5) string devicePciBusId = protoDefaultValue!(string);
    @Proto(6) string blasVersion = protoDefaultValue!(string);
}
