// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/cluster.proto

module tensorflow.cluster;

import google.protobuf;

enum protocVersion = 3012004;

class JobDef
{
    @Proto(1) string name = protoDefaultValue!(string);
    @Proto(2) string[int] tasks = protoDefaultValue!(string[int]);
}

class ClusterDef
{
    @Proto(1) JobDef[] job = protoDefaultValue!(JobDef[]);
}
