// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/control_flow.proto

module tensorflow.control_flow;

import google.protobuf;

enum protocVersion = 3012004;

class ValuesDef
{
    @Proto(1) string[] values = protoDefaultValue!(string[]);
    @Proto(2) string[string] externalValues = protoDefaultValue!(string[string]);
}

class ControlFlowContextDef
{
    enum CtxtCase
    {
        ctxtNotSet = 0,
        condCtxt = 1,
        whileCtxt = 2,
    }
    CtxtCase _ctxtCase = CtxtCase.ctxtNotSet;
    @property CtxtCase ctxtCase() { return _ctxtCase; }
    void clearCtxt() { _ctxtCase = CtxtCase.ctxtNotSet; }
    @Oneof("_ctxtCase") union
    {
        @Proto(1) CondContextDef _condCtxt = protoDefaultValue!(CondContextDef); mixin(oneofAccessors!_condCtxt);
        @Proto(2) WhileContextDef _whileCtxt; mixin(oneofAccessors!_whileCtxt);
    }
}

class CondContextDef
{
    @Proto(1) string contextName = protoDefaultValue!(string);
    @Proto(2) string predName = protoDefaultValue!(string);
    @Proto(3) string pivotName = protoDefaultValue!(string);
    @Proto(4) int branch = protoDefaultValue!(int);
    @Proto(5) ValuesDef valuesDef = protoDefaultValue!(ValuesDef);
    @Proto(6) ControlFlowContextDef[] nestedContexts = protoDefaultValue!(ControlFlowContextDef[]);
}

class WhileContextDef
{
    @Proto(1) string contextName = protoDefaultValue!(string);
    @Proto(2) int parallelIterations = protoDefaultValue!(int);
    @Proto(3) bool backProp = protoDefaultValue!(bool);
    @Proto(4) bool swapMemory = protoDefaultValue!(bool);
    @Proto(5) string pivotName = protoDefaultValue!(string);
    @Proto(6) string pivotForPredName = protoDefaultValue!(string);
    @Proto(7) string pivotForBodyName = protoDefaultValue!(string);
    @Proto(8) string[] loopExitNames = protoDefaultValue!(string[]);
    @Proto(9) ValuesDef valuesDef = protoDefaultValue!(ValuesDef);
    @Proto(10) string[] loopEnterNames = protoDefaultValue!(string[]);
    @Proto(11) string maximumIterationsName = protoDefaultValue!(string);
    @Proto(12) ControlFlowContextDef[] nestedContexts = protoDefaultValue!(ControlFlowContextDef[]);
}
