// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/critical_section.proto

module tensorflow.critical_section;

import google.protobuf;

enum protocVersion = 3012004;

class CriticalSectionDef
{
    @Proto(1) string criticalSectionName = protoDefaultValue!(string);
}

class CriticalSectionExecutionDef
{
    @Proto(1) string executeInCriticalSectionName = protoDefaultValue!(string);
    @Proto(2) bool exclusiveResourceAccess = protoDefaultValue!(bool);
}
