// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/debug_event.proto

module tensorflow.debug_event;

import google.protobuf;
import tensorflow.tensor;
import tensorflow.graph_debug_info;

enum protocVersion = 3012004;

class DebugEvent
{
    @Proto(1) double wallTime = protoDefaultValue!(double);
    @Proto(2) long step = protoDefaultValue!(long);
    enum WhatCase
    {
        whatNotSet = 0,
        debugMetadata = 3,
        sourceFile = 4,
        stackFrameWithId = 6,
        graphOpCreation = 7,
        debuggedGraph = 8,
        execution = 9,
        graphExecutionTrace = 10,
        graphId = 11,
    }
    WhatCase _whatCase = WhatCase.whatNotSet;
    @property WhatCase whatCase() { return _whatCase; }
    void clearWhat() { _whatCase = WhatCase.whatNotSet; }
    @Oneof("_whatCase") union
    {
        @Proto(3) DebugMetadata _debugMetadata = protoDefaultValue!(DebugMetadata); mixin(oneofAccessors!_debugMetadata);
        @Proto(4) SourceFile _sourceFile; mixin(oneofAccessors!_sourceFile);
        @Proto(6) StackFrameWithId _stackFrameWithId; mixin(oneofAccessors!_stackFrameWithId);
        @Proto(7) GraphOpCreation _graphOpCreation; mixin(oneofAccessors!_graphOpCreation);
        @Proto(8) DebuggedGraph _debuggedGraph; mixin(oneofAccessors!_debuggedGraph);
        @Proto(9) Execution _execution; mixin(oneofAccessors!_execution);
        @Proto(10) GraphExecutionTrace _graphExecutionTrace; mixin(oneofAccessors!_graphExecutionTrace);
        @Proto(11) string _graphId; mixin(oneofAccessors!_graphId);
    }
}

class DebugMetadata
{
    @Proto(1) string tensorflowVersion = protoDefaultValue!(string);
    @Proto(2) string fileVersion = protoDefaultValue!(string);
}

class SourceFile
{
    @Proto(1) string filePath = protoDefaultValue!(string);
    @Proto(2) string hostName = protoDefaultValue!(string);
    @Proto(3) string[] lines = protoDefaultValue!(string[]);
}

class StackFrameWithId
{
    @Proto(1) string id = protoDefaultValue!(string);
    @Proto(2) GraphDebugInfo.FileLineCol fileLineCol = protoDefaultValue!(GraphDebugInfo.FileLineCol);
}

class CodeLocation
{
    @Proto(1) string hostName = protoDefaultValue!(string);
    @Proto(2) string[] stackFrameIds = protoDefaultValue!(string[]);
}

class GraphOpCreation
{
    @Proto(1) string opType = protoDefaultValue!(string);
    @Proto(2) string opName = protoDefaultValue!(string);
    @Proto(3) string graphName = protoDefaultValue!(string);
    @Proto(4) string graphId = protoDefaultValue!(string);
    @Proto(5) string deviceName = protoDefaultValue!(string);
    @Proto(6) string[] inputNames = protoDefaultValue!(string[]);
    @Proto(7) int numOutputs = protoDefaultValue!(int);
    @Proto(8) CodeLocation codeLocation = protoDefaultValue!(CodeLocation);
}

class DebuggedGraph
{
    @Proto(1) string graphId = protoDefaultValue!(string);
    @Proto(2) string graphName = protoDefaultValue!(string);
    @Proto(3) string[] instrumentedOps = protoDefaultValue!(string[]);
    @Proto(4) bytes originalGraphDef = protoDefaultValue!(bytes);
    @Proto(5) bytes instrumentedGraphDef = protoDefaultValue!(bytes);
}

class Execution
{
    @Proto(1) string opType = protoDefaultValue!(string);
    @Proto(2) int numOutputs = protoDefaultValue!(int);
    @Proto(3) string graphId = protoDefaultValue!(string);
    @Proto(4, Wire.none, Yes.packed) long[] inputTensorIds = protoDefaultValue!(long[]);
    @Proto(5, Wire.none, Yes.packed) long[] outputTensorIds = protoDefaultValue!(long[]);
    @Proto(6) TensorDebugMode tensorDebugMode = protoDefaultValue!(TensorDebugMode);
    @Proto(7) TensorProto[] tensorProtos = protoDefaultValue!(TensorProto[]);
    @Proto(8) CodeLocation codeLocation = protoDefaultValue!(CodeLocation);
}

class GraphExecutionTrace
{
    @Proto(1) string tfdbgContextId = protoDefaultValue!(string);
    @Proto(2) string opName = protoDefaultValue!(string);
    @Proto(3) int outputSlot = protoDefaultValue!(int);
    @Proto(4) TensorDebugMode tensorDebugMode = protoDefaultValue!(TensorDebugMode);
    @Proto(5) TensorProto tensorProto = protoDefaultValue!(TensorProto);
    @Proto(6) string deviceName = protoDefaultValue!(string);
}

enum TensorDebugMode
{
    UNSPECIFIED = 0,
    NO_TENSOR = 1,
    CURT_HEALTH = 2,
    CONCISE_HEALTH = 3,
    FULL_HEALTH = 4,
    SHAPE = 5,
    FULL_NUMERICS = 6,
    FULL_TENSOR = 7,
    REDUCE_INF_NAN_THREE_SLOTS = 8,
}
