// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/debug.proto

module tensorflow.debug_;

import google.protobuf;

enum protocVersion = 3012004;

class DebugTensorWatch
{
    @Proto(1) string nodeName = protoDefaultValue!(string);
    @Proto(2) int outputSlot = protoDefaultValue!(int);
    @Proto(3) string[] debugOps = protoDefaultValue!(string[]);
    @Proto(4) string[] debugUrls = protoDefaultValue!(string[]);
    @Proto(5) bool tolerateDebugOpCreationFailures = protoDefaultValue!(bool);
}

class DebugOptions
{
    @Proto(4) DebugTensorWatch[] debugTensorWatchOpts = protoDefaultValue!(DebugTensorWatch[]);
    @Proto(10) long globalStep = protoDefaultValue!(long);
    @Proto(11) bool resetDiskByteUsage = protoDefaultValue!(bool);
}

class DebuggedSourceFile
{
    @Proto(1) string host = protoDefaultValue!(string);
    @Proto(2) string filePath = protoDefaultValue!(string);
    @Proto(3) long lastModified = protoDefaultValue!(long);
    @Proto(4) long bytes = protoDefaultValue!(long);
    @Proto(5) string[] lines = protoDefaultValue!(string[]);
}

class DebuggedSourceFiles
{
    @Proto(1) DebuggedSourceFile[] sourceFiles = protoDefaultValue!(DebuggedSourceFile[]);
}
