// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/device_attributes.proto

module tensorflow.device_attributes;

import google.protobuf;

enum protocVersion = 3012004;

class InterconnectLink
{
    @Proto(1) int deviceId = protoDefaultValue!(int);
    @Proto(2) string type = protoDefaultValue!(string);
    @Proto(3) int strength = protoDefaultValue!(int);
}

class LocalLinks
{
    @Proto(1) InterconnectLink[] link = protoDefaultValue!(InterconnectLink[]);
}

class DeviceLocality
{
    @Proto(1) int busId = protoDefaultValue!(int);
    @Proto(2) int numaNode = protoDefaultValue!(int);
    @Proto(3) LocalLinks links = protoDefaultValue!(LocalLinks);
}

class DeviceAttributes
{
    @Proto(1) string name = protoDefaultValue!(string);
    @Proto(2) string deviceType = protoDefaultValue!(string);
    @Proto(4) long memoryLimit = protoDefaultValue!(long);
    @Proto(5) DeviceLocality locality = protoDefaultValue!(DeviceLocality);
    @Proto(6, Wire.fixed) ulong incarnation = protoDefaultValue!(ulong);
    @Proto(7) string physicalDeviceDesc = protoDefaultValue!(string);
}
