// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/named_tensor.proto

module tensorflow.named_tensor;

import google.protobuf;
import tensorflow.tensor;

enum protocVersion = 3012004;

class NamedTensorProto
{
    @Proto(1) string name = protoDefaultValue!(string);
    @Proto(2) TensorProto tensor = protoDefaultValue!(TensorProto);
}
