// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/node_def.proto

module tensorflow.node_def;

import google.protobuf;
import tensorflow.attr_value;

enum protocVersion = 3012004;

class NodeDef
{
    @Proto(1) string name = protoDefaultValue!(string);
    @Proto(2) string op = protoDefaultValue!(string);
    @Proto(3) string[] input = protoDefaultValue!(string[]);
    @Proto(4) string device = protoDefaultValue!(string);
    @Proto(5) AttrValue[string] attr = protoDefaultValue!(AttrValue[string]);
    @Proto(6) NodeDef.ExperimentalDebugInfo experimentalDebugInfo = protoDefaultValue!(NodeDef.ExperimentalDebugInfo);

    static class ExperimentalDebugInfo
    {
        @Proto(1) string[] originalNodeNames = protoDefaultValue!(string[]);
        @Proto(2) string[] originalFuncNames = protoDefaultValue!(string[]);
    }
}
