// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/queue_runner.proto

module tensorflow.queue_runner;

import google.protobuf;
import tensorflow.error.error_codes;

enum protocVersion = 3012004;

class QueueRunnerDef
{
    @Proto(1) string queueName = protoDefaultValue!(string);
    @Proto(2) string[] enqueueOpName = protoDefaultValue!(string[]);
    @Proto(3) string closeOpName = protoDefaultValue!(string);
    @Proto(4) string cancelOpName = protoDefaultValue!(string);
    @Proto(5) Code[] queueClosedExceptionTypes = protoDefaultValue!(Code[]);
}
