// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/reader_base.proto

module tensorflow.reader_base;

import google.protobuf;

enum protocVersion = 3012004;

class ReaderBaseState
{
    @Proto(1) long workStarted = protoDefaultValue!(long);
    @Proto(2) long workFinished = protoDefaultValue!(long);
    @Proto(3) long numRecordsProduced = protoDefaultValue!(long);
    @Proto(4) bytes currentWork = protoDefaultValue!(bytes);
}
