// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/remote_fused_graph_execute_info.proto

module tensorflow.remote_fused_graph_execute_info;

import google.protobuf;
import tensorflow.graph;
import tensorflow.tensor_shape;
import tensorflow.types;

enum protocVersion = 3012004;

class RemoteFusedGraphExecuteInfo
{
    @Proto(1) GraphDef remoteGraph = protoDefaultValue!(GraphDef);
    @Proto(2) string[] graphInputNodeName = protoDefaultValue!(string[]);
    @Proto(3) string[] graphOutputNodeName = protoDefaultValue!(string[]);
    @Proto(4) string executorName = protoDefaultValue!(string);
    @Proto(5) bytes serializedExecutorParameters = protoDefaultValue!(bytes);
    @Proto(6) RemoteFusedGraphExecuteInfo.TensorShapeTypeProto[] defaultGraphInputTensorShape = protoDefaultValue!(RemoteFusedGraphExecuteInfo.TensorShapeTypeProto[]);
    @Proto(7) RemoteFusedGraphExecuteInfo.TensorShapeTypeProto[] defaultGraphOutputTensorShape = protoDefaultValue!(RemoteFusedGraphExecuteInfo.TensorShapeTypeProto[]);

    static class TensorShapeTypeProto
    {
        @Proto(1) DataType dtype = protoDefaultValue!(DataType);
        @Proto(2) TensorShapeProto shape = protoDefaultValue!(TensorShapeProto);
    }
}
