// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/replay_log.proto

module tensorflow.replay_log;

import google.protobuf;
import tensorflow.master;

enum protocVersion = 3012004;

class NewReplaySession
{
    @Proto(1) ListDevicesResponse devices = protoDefaultValue!(ListDevicesResponse);
    @Proto(2) string sessionHandle = protoDefaultValue!(string);
}

class ReplayOp
{
    enum OpCase
    {
        opNotSet = 0,
        createSession = 1,
        extendSession = 2,
        partialRunSetup = 3,
        runStep = 4,
        closeSession = 5,
        listDevices = 6,
        resetRequest = 7,
        makeCallable = 8,
        runCallable = 9,
        releaseCallable = 10,
        newReplaySession = 11,
    }
    OpCase _opCase = OpCase.opNotSet;
    @property OpCase opCase() { return _opCase; }
    void clearOp() { _opCase = OpCase.opNotSet; }
    @Oneof("_opCase") union
    {
        @Proto(1) CreateSessionRequest _createSession = protoDefaultValue!(CreateSessionRequest); mixin(oneofAccessors!_createSession);
        @Proto(2) ExtendSessionRequest _extendSession; mixin(oneofAccessors!_extendSession);
        @Proto(3) PartialRunSetupRequest _partialRunSetup; mixin(oneofAccessors!_partialRunSetup);
        @Proto(4) RunStepRequest _runStep; mixin(oneofAccessors!_runStep);
        @Proto(5) CloseSessionRequest _closeSession; mixin(oneofAccessors!_closeSession);
        @Proto(6) ListDevicesRequest _listDevices; mixin(oneofAccessors!_listDevices);
        @Proto(7) ResetRequest _resetRequest; mixin(oneofAccessors!_resetRequest);
        @Proto(8) MakeCallableRequest _makeCallable; mixin(oneofAccessors!_makeCallable);
        @Proto(9) RunCallableRequest _runCallable; mixin(oneofAccessors!_runCallable);
        @Proto(10) ReleaseCallableRequest _releaseCallable; mixin(oneofAccessors!_releaseCallable);
        @Proto(11) NewReplaySession _newReplaySession; mixin(oneofAccessors!_newReplaySession);
    }
    enum ResponseCase
    {
        responseNotSet = 0,
        createSessionResponse = 21,
        extendSessionResponse = 22,
        partialRunSetupResponse = 23,
        runStepResponse = 24,
        closeSessionResponse = 25,
        listDevicesResponse = 26,
        resetRequestResponse = 27,
        makeCallableResponse = 28,
        runCallableResponse = 29,
        releaseCallableResponse = 30,
    }
    ResponseCase _responseCase = ResponseCase.responseNotSet;
    @property ResponseCase responseCase() { return _responseCase; }
    void clearResponse() { _responseCase = ResponseCase.responseNotSet; }
    @Oneof("_responseCase") union
    {
        @Proto(21) CreateSessionResponse _createSessionResponse = protoDefaultValue!(CreateSessionResponse); mixin(oneofAccessors!_createSessionResponse);
        @Proto(22) ExtendSessionResponse _extendSessionResponse; mixin(oneofAccessors!_extendSessionResponse);
        @Proto(23) PartialRunSetupResponse _partialRunSetupResponse; mixin(oneofAccessors!_partialRunSetupResponse);
        @Proto(24) RunStepResponse _runStepResponse; mixin(oneofAccessors!_runStepResponse);
        @Proto(25) CloseSessionResponse _closeSessionResponse; mixin(oneofAccessors!_closeSessionResponse);
        @Proto(26) ListDevicesResponse _listDevicesResponse; mixin(oneofAccessors!_listDevicesResponse);
        @Proto(27) ResetResponse _resetRequestResponse; mixin(oneofAccessors!_resetRequestResponse);
        @Proto(28) MakeCallableResponse _makeCallableResponse; mixin(oneofAccessors!_makeCallableResponse);
        @Proto(29) RunCallableResponse _runCallableResponse; mixin(oneofAccessors!_runCallableResponse);
        @Proto(30) ReleaseCallableResponse _releaseCallableResponse; mixin(oneofAccessors!_releaseCallableResponse);
    }
    @Proto(31) double startTimeUs = protoDefaultValue!(double);
    @Proto(32) double endTimeUs = protoDefaultValue!(double);
}
