// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/rewriter_config.proto

module tensorflow.rewriter_config;

import google.protobuf;
import tensorflow.attr_value;
import tensorflow.verifier_config;

enum protocVersion = 3012004;

class AutoParallelOptions
{
    @Proto(1) bool enable = protoDefaultValue!(bool);
    @Proto(2) int numReplicas = protoDefaultValue!(int);
}

class ScopedAllocatorOptions
{
    @Proto(1) string[] enableOp = protoDefaultValue!(string[]);
}

class RewriterConfig
{
    @Proto(1) Toggle layoutOptimizer = protoDefaultValue!(Toggle);
    @Proto(2) bool disableModelPruning = protoDefaultValue!(bool);
    @Proto(3) Toggle constantFolding = protoDefaultValue!(Toggle);
    @Proto(4) MemOptType memoryOptimization = protoDefaultValue!(MemOptType);
    @Proto(5) AutoParallelOptions autoParallel = protoDefaultValue!(AutoParallelOptions);
    @Proto(6) string memoryOptimizerTargetNodeNameScope = protoDefaultValue!(string);
    @Proto(7) Toggle arithmeticOptimization = protoDefaultValue!(Toggle);
    @Proto(8) Toggle dependencyOptimization = protoDefaultValue!(Toggle);
    @Proto(9) Toggle loopOptimization = protoDefaultValue!(Toggle);
    @Proto(10) Toggle functionOptimization = protoDefaultValue!(Toggle);
    @Proto(11) Toggle debugStripper = protoDefaultValue!(Toggle);
    @Proto(12) NumIterationsType metaOptimizerIterations = protoDefaultValue!(NumIterationsType);
    @Proto(13) Toggle shapeOptimization = protoDefaultValue!(Toggle);
    @Proto(14) Toggle remapping = protoDefaultValue!(Toggle);
    @Proto(15) Toggle scopedAllocatorOptimization = protoDefaultValue!(Toggle);
    @Proto(16) ScopedAllocatorOptions scopedAllocatorOpts = protoDefaultValue!(ScopedAllocatorOptions);
    @Proto(17) int minGraphNodes = protoDefaultValue!(int);
    @Proto(18) Toggle pinToHostOptimization = protoDefaultValue!(Toggle);
    @Proto(19) bool disableMetaOptimizer = protoDefaultValue!(bool);
    @Proto(20) long metaOptimizerTimeoutMs = protoDefaultValue!(long);
    @Proto(21) bool failOnOptimizerErrors = protoDefaultValue!(bool);
    @Proto(22) Toggle implementationSelector = protoDefaultValue!(Toggle);
    @Proto(23) Toggle autoMixedPrecision = protoDefaultValue!(Toggle);
    @Proto(100) string[] optimizers = protoDefaultValue!(string[]);
    @Proto(200) RewriterConfig.CustomGraphOptimizer[] customOptimizers = protoDefaultValue!(RewriterConfig.CustomGraphOptimizer[]);
    @Proto(300) VerifierConfig interOptimizerVerifierConfig = protoDefaultValue!(VerifierConfig);
    @Proto(301) VerifierConfig postOptimizationVerifierConfig = protoDefaultValue!(VerifierConfig);

    static class CustomGraphOptimizer
    {
        @Proto(1) string name = protoDefaultValue!(string);
        @Proto(2) AttrValue[string] parameterMap = protoDefaultValue!(AttrValue[string]);
    }

    enum Toggle
    {
        DEFAULT = 0,
        ON = 1,
        OFF = 2,
        AGGRESSIVE = 3,
    }

    enum NumIterationsType
    {
        DEFAULT_NUM_ITERS = 0,
        ONE = 1,
        TWO = 2,
    }

    enum MemOptType
    {
        DEFAULT_MEM_OPT = 0,
        NO_MEM_OPT = 1,
        MANUAL = 2,
        SWAPPING_HEURISTICS = 4,
        RECOMPUTATION_HEURISTICS = 5,
        SCHEDULING_HEURISTICS = 6,
        HEURISTICS = 3,
    }
}
