// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/saved_object_graph.proto

module tensorflow.saved_object_graph;

import google.protobuf;
import tensorflow.trackable_object_graph;
import tensorflow.struct_;
import tensorflow.tensor_shape;
import tensorflow.types;
import tensorflow.versions;
import tensorflow.variable;

enum protocVersion = 3012004;

class SavedObjectGraph
{
    @Proto(1) SavedObject[] nodes = protoDefaultValue!(SavedObject[]);
    @Proto(2) SavedConcreteFunction[string] concreteFunctions = protoDefaultValue!(SavedConcreteFunction[string]);
}

class SavedObject
{
    @Proto(1) TrackableObjectGraph.TrackableObject.ObjectReference[] children = protoDefaultValue!(TrackableObjectGraph.TrackableObject.ObjectReference[]);
    @Proto(3) TrackableObjectGraph.TrackableObject.SlotVariableReference[] slotVariables = protoDefaultValue!(TrackableObjectGraph.TrackableObject.SlotVariableReference[]);
    enum KindCase
    {
        kindNotSet = 0,
        userObject = 4,
        asset = 5,
        function_ = 6,
        variable = 7,
        bareConcreteFunction = 8,
        constant = 9,
        resource = 10,
    }
    KindCase _kindCase = KindCase.kindNotSet;
    @property KindCase kindCase() { return _kindCase; }
    void clearKind() { _kindCase = KindCase.kindNotSet; }
    @Oneof("_kindCase") union
    {
        @Proto(4) SavedUserObject _userObject = protoDefaultValue!(SavedUserObject); mixin(oneofAccessors!_userObject);
        @Proto(5) SavedAsset _asset; mixin(oneofAccessors!_asset);
        @Proto(6) SavedFunction _function_; mixin(oneofAccessors!_function_);
        @Proto(7) SavedVariable _variable; mixin(oneofAccessors!_variable);
        @Proto(8) SavedBareConcreteFunction _bareConcreteFunction; mixin(oneofAccessors!_bareConcreteFunction);
        @Proto(9) SavedConstant _constant; mixin(oneofAccessors!_constant);
        @Proto(10) SavedResource _resource; mixin(oneofAccessors!_resource);
    }
}

class SavedUserObject
{
    @Proto(1) string identifier = protoDefaultValue!(string);
    @Proto(2) VersionDef version_ = protoDefaultValue!(VersionDef);
    @Proto(3) string metadata = protoDefaultValue!(string);
}

class SavedAsset
{
    @Proto(1) int assetFileDefIndex = protoDefaultValue!(int);
}

class SavedFunction
{
    @Proto(1) string[] concreteFunctions = protoDefaultValue!(string[]);
    @Proto(2) FunctionSpec functionSpec = protoDefaultValue!(FunctionSpec);
}

class SavedConcreteFunction
{
    @Proto(2, Wire.none, Yes.packed) int[] boundInputs = protoDefaultValue!(int[]);
    @Proto(3) StructuredValue canonicalizedInputSignature = protoDefaultValue!(StructuredValue);
    @Proto(4) StructuredValue outputSignature = protoDefaultValue!(StructuredValue);
}

class SavedBareConcreteFunction
{
    @Proto(1) string concreteFunctionName = protoDefaultValue!(string);
    @Proto(2) string[] argumentKeywords = protoDefaultValue!(string[]);
    @Proto(3) long allowedPositionalArguments = protoDefaultValue!(long);
}

class SavedConstant
{
    @Proto(1) string operation = protoDefaultValue!(string);
}

class SavedVariable
{
    @Proto(1) DataType dtype = protoDefaultValue!(DataType);
    @Proto(2) TensorShapeProto shape = protoDefaultValue!(TensorShapeProto);
    @Proto(3) bool trainable = protoDefaultValue!(bool);
    @Proto(4) VariableSynchronization synchronization = protoDefaultValue!(VariableSynchronization);
    @Proto(5) VariableAggregation aggregation = protoDefaultValue!(VariableAggregation);
    @Proto(6) string name = protoDefaultValue!(string);
}

class FunctionSpec
{
    @Proto(1) StructuredValue fullargspec = protoDefaultValue!(StructuredValue);
    @Proto(2) bool isMethod = protoDefaultValue!(bool);
    @Proto(5) StructuredValue inputSignature = protoDefaultValue!(StructuredValue);
}

class SavedResource
{
    @Proto(1) string device = protoDefaultValue!(string);
}
