// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/saved_model.proto

module tensorflow.saved_model;

import google.protobuf;
import tensorflow.meta_graph;

enum protocVersion = 3012004;

class SavedModel
{
    @Proto(1) long savedModelSchemaVersion = protoDefaultValue!(long);
    @Proto(2) MetaGraphDef[] metaGraphs = protoDefaultValue!(MetaGraphDef[]);
}
