// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/step_stats.proto

module tensorflow.step_stats;

import google.protobuf;
import tensorflow.allocation_description;
import tensorflow.tensor_description;

enum protocVersion = 3012004;

class AllocationRecord
{
    @Proto(1) long allocMicros = protoDefaultValue!(long);
    @Proto(2) long allocBytes = protoDefaultValue!(long);
}

class AllocatorMemoryUsed
{
    @Proto(1) string allocatorName = protoDefaultValue!(string);
    @Proto(2) long totalBytes = protoDefaultValue!(long);
    @Proto(3) long peakBytes = protoDefaultValue!(long);
    @Proto(4) long liveBytes = protoDefaultValue!(long);
    @Proto(5) long allocatorBytesInUse = protoDefaultValue!(long);
    @Proto(6) AllocationRecord[] allocationRecords = protoDefaultValue!(AllocationRecord[]);
}

class NodeOutput
{
    @Proto(1) int slot = protoDefaultValue!(int);
    @Proto(3) TensorDescription tensorDescription = protoDefaultValue!(TensorDescription);
}

class MemoryStats
{
    @Proto(1) long tempMemorySize = protoDefaultValue!(long);
    @Proto(2) long deviceTempMemorySize = protoDefaultValue!(long);
    @Proto(3) long persistentMemorySize = protoDefaultValue!(long);
    @Proto(4) long devicePersistentMemorySize = protoDefaultValue!(long);
    @Proto(5, Wire.none, Yes.packed) long[] persistentTensorAllocIds = protoDefaultValue!(long[]);
    @Proto(6) long[] devicePersistentTensorAllocIds = protoDefaultValue!(long[]);
}

class NodeExecStats
{
    @Proto(1) string nodeName = protoDefaultValue!(string);
    @Proto(2) long allStartMicros = protoDefaultValue!(long);
    @Proto(3) long opStartRelMicros = protoDefaultValue!(long);
    @Proto(4) long opEndRelMicros = protoDefaultValue!(long);
    @Proto(5) long allEndRelMicros = protoDefaultValue!(long);
    @Proto(6) AllocatorMemoryUsed[] memory = protoDefaultValue!(AllocatorMemoryUsed[]);
    @Proto(7) NodeOutput[] output = protoDefaultValue!(NodeOutput[]);
    @Proto(8) string timelineLabel = protoDefaultValue!(string);
    @Proto(9) long scheduledMicros = protoDefaultValue!(long);
    @Proto(10) uint threadId = protoDefaultValue!(uint);
    @Proto(11) AllocationDescription[] referencedTensor = protoDefaultValue!(AllocationDescription[]);
    @Proto(12) MemoryStats memoryStats = protoDefaultValue!(MemoryStats);
    @Proto(13) long allStartNanos = protoDefaultValue!(long);
    @Proto(14) long opStartRelNanos = protoDefaultValue!(long);
    @Proto(15) long opEndRelNanos = protoDefaultValue!(long);
    @Proto(16) long allEndRelNanos = protoDefaultValue!(long);
    @Proto(17) long scheduledNanos = protoDefaultValue!(long);
}

class DeviceStepStats
{
    @Proto(1) string device = protoDefaultValue!(string);
    @Proto(2) NodeExecStats[] nodeStats = protoDefaultValue!(NodeExecStats[]);
    @Proto(3) string[uint] threadNames = protoDefaultValue!(string[uint]);
}

class StepStats
{
    @Proto(1) DeviceStepStats[] devStats = protoDefaultValue!(DeviceStepStats[]);
}
