// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/summary.proto

module tensorflow.summary;

import google.protobuf;
import tensorflow.tensor;

enum protocVersion = 3012004;

class SummaryDescription
{
    @Proto(1) string typeHint = protoDefaultValue!(string);
}

class HistogramProto
{
    @Proto(1) double min = protoDefaultValue!(double);
    @Proto(2) double max = protoDefaultValue!(double);
    @Proto(3) double num = protoDefaultValue!(double);
    @Proto(4) double sum = protoDefaultValue!(double);
    @Proto(5) double sumSquares = protoDefaultValue!(double);
    @Proto(6, Wire.none, Yes.packed) double[] bucketLimit = protoDefaultValue!(double[]);
    @Proto(7, Wire.none, Yes.packed) double[] bucket = protoDefaultValue!(double[]);
}

class SummaryMetadata
{
    @Proto(1) SummaryMetadata.PluginData pluginData = protoDefaultValue!(SummaryMetadata.PluginData);
    @Proto(2) string displayName = protoDefaultValue!(string);
    @Proto(3) string summaryDescription = protoDefaultValue!(string);

    static class PluginData
    {
        @Proto(1) string pluginName = protoDefaultValue!(string);
        @Proto(2) bytes content = protoDefaultValue!(bytes);
    }
}

class Summary
{
    @Proto(1) Summary.Value[] value = protoDefaultValue!(Summary.Value[]);

    static class Image
    {
        @Proto(1) int height = protoDefaultValue!(int);
        @Proto(2) int width = protoDefaultValue!(int);
        @Proto(3) int colorspace = protoDefaultValue!(int);
        @Proto(4) bytes encodedImageString = protoDefaultValue!(bytes);
    }

    static class Audio
    {
        @Proto(1) float sampleRate = protoDefaultValue!(float);
        @Proto(2) long numChannels = protoDefaultValue!(long);
        @Proto(3) long lengthFrames = protoDefaultValue!(long);
        @Proto(4) bytes encodedAudioString = protoDefaultValue!(bytes);
        @Proto(5) string contentType = protoDefaultValue!(string);
    }

    static class Value
    {
        @Proto(1) string tag = protoDefaultValue!(string);
        enum ValueCase
        {
            valueNotSet = 0,
            simpleValue = 2,
            obsoleteOldStyleHistogram = 3,
            image = 4,
            histo = 5,
            audio = 6,
            tensor = 8,
        }
        ValueCase _valueCase = ValueCase.valueNotSet;
        @property ValueCase valueCase() { return _valueCase; }
        void clearValue() { _valueCase = ValueCase.valueNotSet; }
        @Oneof("_valueCase") union
        {
            @Proto(2) float _simpleValue = protoDefaultValue!(float); mixin(oneofAccessors!_simpleValue);
            @Proto(3) bytes _obsoleteOldStyleHistogram; mixin(oneofAccessors!_obsoleteOldStyleHistogram);
            @Proto(4) Summary.Image _image; mixin(oneofAccessors!_image);
            @Proto(5) HistogramProto _histo; mixin(oneofAccessors!_histo);
            @Proto(6) Summary.Audio _audio; mixin(oneofAccessors!_audio);
            @Proto(8) TensorProto _tensor; mixin(oneofAccessors!_tensor);
        }
        @Proto(7) string nodeName = protoDefaultValue!(string);
        @Proto(9) SummaryMetadata metadata = protoDefaultValue!(SummaryMetadata);
    }
}
