// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/tensor_slice.proto

module tensorflow.tensor_slice;

import google.protobuf;

enum protocVersion = 3012004;

class TensorSliceProto
{
    @Proto(1) TensorSliceProto.Extent[] extent = protoDefaultValue!(TensorSliceProto.Extent[]);

    static class Extent
    {
        @Proto(1) long start = protoDefaultValue!(long);
        enum HasLengthCase
        {
            hasLengthNotSet = 0,
            length = 2,
        }
        HasLengthCase _hasLengthCase = HasLengthCase.hasLengthNotSet;
        @property HasLengthCase hasLengthCase() { return _hasLengthCase; }
        void clearHasLength() { _hasLengthCase = HasLengthCase.hasLengthNotSet; }
        @Oneof("_hasLengthCase") union
        {
            @Proto(2) long _length = protoDefaultValue!(long); mixin(oneofAccessors!_length);
        }
    }
}
