// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/tensor_shape.proto

module tensorflow.tensor_shape;

import google.protobuf;

enum protocVersion = 3012004;

class TensorShapeProto
{
    @Proto(2) TensorShapeProto.Dim[] dim = protoDefaultValue!(TensorShapeProto.Dim[]);
    @Proto(3) bool unknownRank = protoDefaultValue!(bool);

    static class Dim
    {
        @Proto(1) long size = protoDefaultValue!(long);
        @Proto(2) string name = protoDefaultValue!(string);
    }
}
