// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/tensorflow_server.proto

module tensorflow.tensorflow_server;

import google.protobuf;
import tensorflow.config;
import tensorflow.cluster;

enum protocVersion = 3012004;

class ServerDef
{
    @Proto(1) ClusterDef cluster = protoDefaultValue!(ClusterDef);
    @Proto(2) string jobName = protoDefaultValue!(string);
    @Proto(3) int taskIndex = protoDefaultValue!(int);
    @Proto(4) ConfigProto defaultSessionConfig = protoDefaultValue!(ConfigProto);
    @Proto(5) string protocol = protoDefaultValue!(string);
    @Proto(6) int port = protoDefaultValue!(int);
}
