// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/tensor_bundle.proto

module tensorflow.tensor_bundle;

import google.protobuf;
import tensorflow.tensor_shape;
import tensorflow.tensor_slice;
import tensorflow.types;
import tensorflow.versions;

enum protocVersion = 3012004;

class BundleHeaderProto
{
    @Proto(1) int numShards = protoDefaultValue!(int);
    @Proto(2) Endianness endianness = protoDefaultValue!(Endianness);
    @Proto(3) VersionDef version_ = protoDefaultValue!(VersionDef);

    enum Endianness
    {
        LITTLE = 0,
        BIG = 1,
    }
}

class BundleEntryProto
{
    @Proto(1) DataType dtype = protoDefaultValue!(DataType);
    @Proto(2) TensorShapeProto shape = protoDefaultValue!(TensorShapeProto);
    @Proto(3) int shardId = protoDefaultValue!(int);
    @Proto(4) long offset = protoDefaultValue!(long);
    @Proto(5) long size = protoDefaultValue!(long);
    @Proto(6, Wire.fixed) uint crc32c = protoDefaultValue!(uint);
    @Proto(7) TensorSliceProto[] slices = protoDefaultValue!(TensorSliceProto[]);
}
