// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/transport_options.proto

module tensorflow.transport_options;

import google.protobuf;

enum protocVersion = 3012004;

class RecvBufRespExtra
{
    @Proto(1) bytes[] tensorContent = protoDefaultValue!(bytes[]);
}
