// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/verifier_config.proto

module tensorflow.verifier_config;

import google.protobuf;

enum protocVersion = 3012004;

class VerifierConfig
{
    @Proto(1) long verificationTimeoutInMs = protoDefaultValue!(long);
    @Proto(2) Toggle structureVerifier = protoDefaultValue!(Toggle);

    enum Toggle
    {
        DEFAULT = 0,
        ON = 1,
        OFF = 2,
    }
}
