// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/versions.proto

module tensorflow.versions;

import google.protobuf;

enum protocVersion = 3012004;

class VersionDef
{
    @Proto(1) int producer = protoDefaultValue!(int);
    @Proto(2) int minConsumer = protoDefaultValue!(int);
    @Proto(3, Wire.none, Yes.packed) int[] badConsumers = protoDefaultValue!(int[]);
}
